version: '3'

services:
  gameserver:
    build:
        context: ./competition
        dockerfile: Dockerfile
    ports:
      - 7777:7777
    environment:
      TZ: "Asia/Seoul"
    logging:
      options:
        max-size: "1024m"  
        max-file: "5"
  new_game:
    build:
        context: ./cooperation
        dockerfile: Dockerfile
    ports:
      - 7778:7778
    environment:
      TZ: "Asia/Seoul"
    logging:
      options:
        max-size: "1024m"  
        max-file: "5"
  fastapi:
    build:
        context: ./websocket
        dockerfile: Dockerfile
    ports:
      - 8000:8000
    environment:
      TZ: "Asia/Seoul"
    logging:
      options:
        max-size: "1024m"  
        max-file: "5"
  nginx:
    image: nginx:1.15-alpine
    restart: unless-stopped
    volumes:
      - ../backup/nginx-certbot/data/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../backup/nginx-certbot/data/nginx/app.conf:/etc/nginx/conf.d/default.conf
      - ../backup/nginx-certbot/data/certbot/conf:/etc/letsencrypt
      - ../backup/nginx-certbot/data/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    environment:
      TZ: "Asia/Seoul"
    logging:
      options:
        max-size: "1024m"  
        max-file: "5"
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ../backup/nginx-certbot/data/certbot/conf:/etc/letsencrypt
      - ../backup/nginx-certbot/data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    environment:
      TZ: "Asia/Seoul"
    logging:
      options:
        max-size: "1024m"  
        max-file: "5"

